core/urls.py
from django.urls import path
from .views import SignupView, Index, PostDetailView, ArticleListView, PostDelete

urlpatterns = [
    path('signup', SignupView.as_view()),
    path('t', Index.as_view()),
    path('author/add/', Index.as_view(), name='author-add'),
    path('<slug:slug>/', PostDetailView.as_view(), name='post-detail'),
    path('allpost', ArticleListView.as_view(),name = 'article-list'),
    path('delete/<slug:slug>/', PostDelete.as_view())
]

djre/urls.py
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include
from core.views import SignupView
from djre import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('signup', SignupView.as_view()),
    path('test/', include('core.urls'))

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django_extensions.db.fields import AutoSlugField


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    slug = AutoSlugField(populate_from='title',
                         unique=True, null=True, blank=True)
    postImage = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self):
        return self.title

core/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Post


class UserRegForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=60)
    last_name = forms.CharField(max_length=60)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        # exclude = ['author']

core/views.py
from datetime import timezone

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, DeleteView

from .forms import UserRegForm, PostForm
# Create your views here.
from django.views import View
from .models import Post


class SignupView(View):
    form_class = UserRegForm
    initial = {'key': 'value'}
    template_name = 'signup.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        print("sdfsdfsdfsdfsd")
        print(form)
        if form.is_valid():
            form.save()
            # <process form cleaned data>
            print(form)
            return HttpResponseRedirect('/success/')

        return render(request, self.template_name, {'form': form})


class Index(View):
    form_class = PostForm
    initial = {'key': 'value'}

    def get(self, request, *args, **kwargs):
        aut = request.user.pk
        print(aut)
        form = self.form_class(initial=self.initial)
        return render(request, 'index.html', {'form': form,
                                              'aut': aut})

    def post(self, request, *args, **kwargs):
        aut = request.user.pk
        form = self.form_class(request.POST, request.FILES)
        print(form)
        form.save()
        form = self.form_class(initial=self.initial)
        return render(request, 'index.html', {'form': form,
                                              'aut': aut})


class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        return context


class ArticleListView(ListView):
    model = Post
    paginate_by = 100  # if pagination is desired

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        return context


class PostDelete(DeleteView):
    model = Post
    success_url = '/'

templates/board.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/core/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
</body>
</html>

templates/core/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{{object.title}}<br>
-{{object.author}}<br>
{{object.body}}<br>
<img src="{{object.postImage.url}}" style="width:60%; ">

</body>
</html>

templates/core/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1><b>Articles</b></h1>
<ul>
{% for article in object_list %}
    <li>{{ article.author}} - {{ article.title }}</li>
    <p>
        {{article.body}}
        <a href={{article.slug}}>read more</a>
    </p>
{% empty %}
    <li>No articles yet.</li>
{% endfor %}
</ul>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>



<form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
    {{aut}}
    <input type="text" name="author" maxlength="255" required id="id_title" value={{aut}}>
<p><label for="id_title">Title:</label> <input type="text" name="title" maxlength="255" required id="id_title"></p>
<p><label for="id_body">Body:</label> <textarea name="body" cols="40" rows="10" required id="id_body">
</textarea></p>
<p><label for="id_postImage">PostImage:</label> <input type="file" name="postImage" accept="image/*" id="id_postImage"></p>
        astra
        <button type="submit">Upload</button>
    </form>
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
          <form class="form-signin" method="POST">
              {% csrf_token %}
              <input type="hidden" name="csrfmiddlewaretoken" value="qh1VLmL1YLmLUBk3RUrvdwtT1YKdhGztdakWOM8rX5ZvZl2VNntn7ntXEjbF5UxQ">
                <p><label for="id_first_name">First name:</label> <input type="text" name="first_name" maxlength="60" required id="id_first_name"></p>
<p><label for="id_last_name">Last name:</label> <input type="text" name="last_name" maxlength="60" required id="id_last_name"></p>
<p><label for="id_username">Username:</label> <input type="text" name="username" maxlength="150" autofocus required id="id_username"> </p>
<p><label for="id_email">Email:</label> <input type="email" name="email" required id="id_email"></p>
<p><label for="id_password1">Password:</label> <input type="password" name="password1" autocomplete="new-password" required id="id_password1"> <span class="helptext"></span></p>
<p><label for="id_password2">Password confirmation:</label> <input type="password" name="password2" autocomplete="new-password" required id="id_password2"> </p>
              <input type="submit" value="Submit" >

          </form>
</body>
</html>